#spring.sql.init.mode=never
#debug=true

spring.datasource.url=jdbc:sqlserver://localhost:1433;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=Hardware_web_shop;
spring.datasource.username=sa
spring.datasource.password=SQL
server.port=8081

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt.base64-secret=Gv0AE1qJlPfW/bcYtSgO06KYZLirJ8AeT3R1tcMtGjc=
jwt.access-token-validity-seconds=600
jwt.refresh-token-validity-seconds=28800

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=UTC