spring.application.name=ZadatakHardware

# URL for in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 web console at localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8081
