#spring.sql.init.mode=never
#debug=true

spring.datasource.url=jdbc:sqlserver://localhost:1433;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=Hardware_web_shop;
spring.datasource.username=sa
spring.datasource.password=SQL
server.port=8081